### PR TITLE
Added threshold in line graph

### PR DESCRIPTION
**Pull request by sridharan-dlt**
#### Threshold line added in the line graph using mixed chart concept.

### CODE REVIEW

**Comment by TekMonksGitHub** [comment]
Should we use annotations plugin?

https://github.com/chartjs/chartjs-plugin-annotation

**Comment by TekMonksGitHub** [comment]
Secondly 

(1) Follow the code style please. We can extract and pass the parameters right from the function call, as we do right now for other params.

(2) For missing params the defaults are decided in chart-box.mjs not chart.mjs usually. Chart.mjs should be kept as thin as possible as in the future, we may replace charjs it depends on, with our own library based on D3 or something even lower level.

**Comment by sridharan-dlt** [comment]
For  annotation plugin, 
Let me check. 

(1) Yeah I followed the code style. Right now the extra params I added for threshold line will be extracted from the dashboard.page. 
(2) Ok I understood. Let me handle those defaults for missing params in the chart-box.mjs level.

**Comment by TekMonksGitHub** [comment]
Revise then for #1 and #2. Element params can be extracted right as part of function call. Default should be in the component.

As for annotation plugin versus data - I am not sure I want to pollute chart data just to draw a line which is not part of the chart's actual data.

**Comment by sridharan-dlt** [comment]
### Changes
1. Annotation plugin added. 
2. Defaults are handled in component level.
3. Threshold included in the both line & bar graphs.

**Comment by TekMonksGitHub** [comment]
Gonna merge this, seems OK to me, at first look. May revise if needed later in a separate commit.

**Pull request merged**
